CREATE TABLE `demspirals`.`playerstats` 
( 
    `pid` VARCHAR(255) NOT NULL UNIQUE , 
    `runs` INT NULL DEFAULT NULL , 
    `passes` INT NULL DEFAULT NULL , 
    `receptions` INT NULL , 
	`receptionyards` INT NULL,
	`receptiontargets` INT NULL,
	`receptionyards10p` INT NULL,
	`receptionyards20p` INT NULL,
	`receptionyards30p` INT NULL,
	`receptionyards40p` INT NULL,
	`receptionyards50p` INT NULL,
    `rushyards` INT NULL,
    `rushattempts` INT NULL,
    `rushyards10p` INT NULL,
    `rushyards20p` INT NULL,
    `rushyards30p` INT NULL,
    `rushyards40p` INT NULL,
    `rushyards50p` INT NULL,
    `touchdownpasses` INT NULL,
    `touchdownrushes` INT NULL,
    `fumbles` INT NULL,
    `lastupdated` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`pid`(255))
) ENGINE = InnoDB COMMENT = 'Player collected stats';
